language: php

sudo: false

php:
  - 8.3

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --dev

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpunit

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r build/logs/clover.xml