name: PHP CI with Codacy Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: PHP 8.3

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug
          tools: composer:v2

      - name: Configure Xdebug for coverage
        run: |
          echo "XDEBUG_MODE=coverage" >> $GITHUB_ENV
          
          # 验证 Xdebug 配置
          echo "Xdebug version: $(php -r 'echo phpversion("xdebug");')"
          echo "Xdebug modes: $(php -r 'echo ini_get("xdebug.mode");')"

      - name: Install dependencies
        run: composer update --no-interaction --dev

      - name: Prepare directories
        run: mkdir -p build/logs .phpunit.cache

      - name: Run tests with coverage
        run: |
          vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml
          
          if [ ! -f build/logs/clover.xml ]; then
            echo "❌ Coverage file not generated!"
            exit 1
          fi
          
          head -n 20 build/logs/clover.xml

      - name: Upload coverage to Codacy
        if: success() && github.ref == 'refs/heads/master'
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          curl -Ls https://coverage.codacy.com/get.sh > codacy-reporter
          chmod +x codacy-reporter
          ./codacy-reporter report -r build/logs/clover.xml
          
          # 验证上传结果
          if [ $? -ne 0 ]; then
            echo "❌ Failed to upload coverage to Codacy"
            exit 1
          fi